### ISSUE TITLE
async_reduce.cu example error

### ISSUE THREAD

**Issue by sdalton1** [agency-library/agency#292]
I'm running into a bus error when I execute the cuda/async_reduce.cu example. The error is resolved when I add a cudaDeviceSynchronize after the to bulk_async.

CUDA 8, Ubuntu 16.04

**Comment by jaredhoberock** [comment]
Hmm, I don't see that behavior:

```
jhoberock@jhoberock-dt:~/dev/git/agency-tot/examples/cuda$ scons -D async_reduce
scons: Entering directory `/home/jhoberock/dev/git/agency-tot/examples'
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
nvcc -o cuda/async_reduce.o -c -arch=sm_52 --expt-extended-lambda -std=c++11 -O3 -I /home/jhoberock/dev/git/agency-tot cuda/async_reduce.cu
nvcc -arch=sm_52 -o cuda/async_reduce cuda/async_reduce.o -lstdc++ -lpthread
scons: done building targets.
jhoberock@jhoberock-dt:~/dev/git/agency-tot/examples/cuda$ ./async_reduce 
OK
```

What GPU are you using?

**Comment by sdalton1** [comment]
I'm using a 960M but I just remember I'm also using CUDA 8RC not the latest release. Could that be the issue?

**Comment by jaredhoberock** [comment]
I think the relevant difference is probably the GPUs we're both using. I've been testing with Pascal, which handles unified memory than does Maxwell.

It could be that we need to wait on the future differently depending on the GPU architecture. `.wait()` boils down to a `cudaEventSynchronize()`, but maybe when the future is hosted on a Maxwell we also need to do a `cudaDeviceSynchronize()`?

**Comment by jaredhoberock** [comment]
By the way, is this a newly introduced problem, or has it always existed?

**Comment by sdalton1** [comment]
I think this is a new error. I've run this example before with no errors. I can try backtracking to see when it may have been introduced.

**Comment by jaredhoberock** [comment]
Thanks. Please try to find the commit which introduced the regression, if it's not too much trouble. My guess is that it is this one or one nearby: 0c3bfd7ff8f077b562b1b2eb49fc21a0dffee77d

**Comment by sdalton1** [comment]
Here's the first commit that fails:
https://github.com/agency-library/agency/commit/31df09c1388c9081a13e0d0af2cd38ea71723881

**Comment by jaredhoberock** [comment]
Thanks Steve. I'm not sure why that change would expose the bug, because it doesn't actually introduce any observable effects.

Anyway, I'm sure the resolution will just be to introduce some extra synchronization into `cuda::async_future` for Maxwell devices.

**Comment by jaredhoberock** [comment]
Another less-intrusive way to fix this without resorting to propagating a new type of smart pointer throughout the codebase may be `cudaStreamAttachMemAsync`. It wouldn't fix the issue of the host touching device memory while the GPU is active comprehensively, but it might be a point solution for this particular problem.

What we could do is that when the `async_future`'s asynchronous state is created, the state would call `cudaStreamAttachMemAsync` to attach its data pointer to the `async_future`'s stream. We'd need to tell the `asynchronous_state` about the stream on which the continuation will run, which may require altering the order in which those items are created.

**Comment by jaredhoberock** [comment]
Pseudocode for `async_future::bulk_then()` might look like this:

```
create a new stream s on given device for the continuation
create asynchronous states for result and outer arg on s
event().then_on_and_invalidate(..., s);
schedule asynchronous states' destruction
return a future tracking the continuation
```

`asynchronous_state`'s constructor will need to be augmented to accept a stream parameter.
