### ISSUE TITLE
Add tiles over indicies

### ISSUE THREAD

**Issue by alobb** [agency-library/agency#320]
Hi,

I'm working with Agency on a school project.  One thing I've found that could be useful is to allow tiling over indices instead of the data itself.  Specifically, having a construct like `agency::experimental::tile_evenly(start_idx, end_idx, num_agents)`.  This would be helpful in situations where there are many input vectors and thus would have a lot of boilerplate code for using tiles as they are now.  Additionally, it would make converting loops that use numerical indices simpler.  Let me know how this sounds/if I've overlooked something from the source code now that would allow this.

**Comment by jaredhoberock** [comment]
Hi, thanks for the feedback. I agree a facility to create ranges of indices would be useful, but I don't believe anything like that exists yet.

Suppose something like this was possible:

```
using namespace agency::experimental;

auto tiled_indices = tile_evenly(something(start_idx, end_dx), num_agents);
```

Where `something(begin, end)` creates the half-open interval `[begin, end)`. In other words, `tile_evenly()` wouldn't necessarily work on indices directly, but could indirectly tile a range of indices just like it can for data.

Do you think that would serve your use case?

**Comment by alobb** [comment]
Yep, thats exactly what I'm looking for!

**Comment by jaredhoberock** [comment]
Great - there's a new `experimental::interval()` function that should produce what you're looking for.

**Comment by jaredhoberock** [comment]
By the way, I didn't test `interval()` with `tile_evenly()`, so let me know if you run into problems.

**Comment by alobb** [comment]
Sorry for the long hiatus; when I try to use `interval` with `tile_evenly`, I get template errors; still trying to make a minified example, but here's an example error from the line where I call `tile_evenly(interval(...), NUM_AGENTS)`:

```
agency/agency/experimental/ranges/all.hpp:63:51: error: no matching function for call to 'all(agency::experimental::iota_view<int>)'
 using all_t = agency::detail::decay_t<decltype(all(std::declval<Range>()))>;
```
