### ISSUE TITLE
heterogeneous execution policy?

### ISSUE THREAD

**Issue by dcanelhas** [agency-library/agency#365]
Hi, This is more of a question than an enhancement proposal:

Is there an elegant way of transferring only a part of the data to be processed to a cuda device and keeping part of it on the host and defining a single variable that determines the split? This would be useful for benchmarking the relative gains of the cudamemcpy overheads vs cpu thread management and the relative clock-speeds/parallelism.

An ideal workload balance might look like this, for example:
```
¤¤|===|xxxxx|===|.| GPU
¤|xxxxxxxxxxxxxx|x| CPU

¤ - initialization
= - memory transfer
x - execution
. -idle
```

**Comment by jaredhoberock** [comment]
There's nothing really like that in Agency. In fact, the default CUDA allocator implemented with `cudaMallocManaged` moves memory automatically with demand paging. Depending on your needs, you might be able to do what you want by splitting up a container of device memory and having the CPU and GPU work on different parts of it.

The process would go something like this:

    using namespace agency;

    // create some data
    std::vector<int, cuda::allocator<int>> data = ...

    // split up the data
    int split_position = ...

    // do something asynchronously on the GPU
    auto gpu_work = bulk_async(cuda::par(data.size() - split_position), ...);

    // do something on the CPU
    for(int i = 0; i < split_position; ++i)
    {
      ...
    }

    // wait for GPU to finish
    gpu_work.wait();

Note that this kind of paging requires a Pascal or later GPU.

**Comment by jaredhoberock** [comment]
Also, it ought to be possible to build a [user-defined executor](https://github.com/agency-library/agency/blob/master/examples/fork_executor.cpp) for heterogeneous execution. The idea would be to create an executor type which is itself contains two (or more) different types of executors. Inside of the executor's work creation function (e.g. `bulk_sync_execute`) work would get divided among the different constituent executors.

The tricky part is deciding how to compute a good split. I'm skeptical one could come up with a general policy that would always work well with the limited information that would be available to such an executor. Probably the split parameter would need to be given by the user.

**Comment by dcanelhas** [comment]
Thanks for the answer, It was more of a curiosity than an urgent need. I like the direction this is going.

If you want my opinion, I think a user-defined split is really ok. 
If a developer then wants to benchmark different splits for a specific architecture or do some run-time probing to define a heuristic based on bus speeds, core numbers and clocks etc. is up to her.
